name: Promote Python Package

on:
  repository_dispatch:
    types: [package_synced]

env:
  CLOUDSMITH_NAMESPACE: ${{ vars.CLOUDSMITH_NAMESPACE }}
  CLOUDSMITH_STAGING_REPO: 'staging'
  CLOUDSMITH_PRODUCTION_REPO: 'production'
  CLOUDSMITH_SERVICE_SLUG: ${{ vars.CLOUDSMITH_SERVICE_SLUG }}
  PACKAGE_NAME: 'example_package'

permissions:
  id-token: write

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Install Cloudsmith CLI
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.1
        with:
          oidc-namespace: ${{ env.CLOUDSMITH_NAMESPACE }}
          oidc-service-slug: ${{ env.CLOUDSMITH_SERVICE_SLUG }}
      - name: Tag and promote package
        run: |
          PACKAGE_SLUG="${{ github.event.client_payload.slug }}"
          if [ -z "$PACKAGE_SLUG" ]; then
            echo "Failed to find package identifier"
            exit 1
          fi
          echo "Tagging package $PACKAGE_SLUG as ready-for-production"

          cloudsmith tags add \
            ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$PACKAGE_SLUG \
            "ready-for-production"

          PACKAGE_QUERY="tags:ready-for-production"

          cloudsmith move --yes \
            ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }} \
            --query "$PACKAGE_QUERY" \
            ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_PRODUCTION_REPO }}

        shell: bash
